{% set version = '0.6.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-questionr
  version: {{ version|replace("-", "_") }}

source:
  fn: questionr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/questionr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/questionr/questionr_{{ version }}.tar.gz
  sha256: 6939d4b089aabfb9afedfaf263e89da65b26df50f0a087e00eacbd06294f53ed

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: memisc, testthat, roxygen2, dplyr, tidyr, janitor, forcats, knitr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-classint
    - r-highr
    - r-htmltools
    - r-labelled >=1.0.0
    - r-miniui
    - r-rstudioapi
    - r-shiny >=1.0.5

  run:
    - r-base
    - r-classint
    - r-highr
    - r-htmltools
    - r-labelled >=1.0.0
    - r-miniui
    - r-rstudioapi
    - r-shiny >=1.0.5

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('questionr')"           # [not win]
    - "\"%R%\" -e \"library('questionr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://juba.github.io/questionr/
  license: GPL (>= 2)
  summary: 'Set of functions to make the processing and analysis of surveys easier : interactive
    shiny apps and addins for data recoding, contingency tables, dataset metadata handling,
    and several convenience functions.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: questionr
# Maintainer: Julien Barnier <julien.barnier@ens-lyon.fr>
# Authors@R: c(person("Julien", "Barnier", email="julien.barnier@ens-lyon.fr", role=c("aut","cre")), person("Francois", "Briatte", email="f.briatte@gmail.com", role="aut"), person("Joseph", "Larmarange", email="joseph@larmarange.net", role="aut"))
# Version: 0.6.3
# Date: 2018-07-17
# License: GPL (>= 2)
# Encoding: UTF-8
# Title: Functions to Make Surveys Processing Easier
# Description: Set of functions to make the processing and analysis of surveys easier : interactive shiny apps and addins for data recoding, contingency tables, dataset metadata handling, and several convenience functions.
# Depends: R (>= 2.10)
# Imports: shiny (>= 1.0.5), miniUI, rstudioapi, highr, classInt, htmltools, graphics, stats, utils, labelled (>= 1.0.0)
# Suggests: memisc, testthat, roxygen2, dplyr, tidyr, janitor, forcats, knitr
# SystemRequirements: xclip (Linux)
# VignetteBuilder: knitr
# URL: https://juba.github.io/questionr/
# BugReports: https://github.com/juba/questionr/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-07-17 13:20:20 UTC; julien
# Author: Julien Barnier [aut, cre], Francois Briatte [aut], Joseph Larmarange [aut]
# Repository: CRAN
# Date/Publication: 2018-07-17 17:50:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
